// Code generated by "make version". DO NOT EDIT.

package api

const Version = "18.2.4-maia"

const VersionMajor = 18
const VersionMinor = 2
const VersionPatch = 4
const VersionPreRelease = "maia"
const VersionMetadata = ""
